### ISSUE TITLE
Developer Platform

### ISSUE THREAD

**Issue by sanderpick** [textileio/meta#36]
The next logical step in our mission to make writing, deploying, and scaling apps on IPFS a reality is to introduce the concepts of a "developer" and an "application" as first-class citizens. 

This is all about providing tooling for developers while maintaining the ability for a user to choose where their data is stored. Once we have the basics in place, more exciting features are possible:
- Push notifications
- Application analytics
- Remote config
- Crash reporting

### Opening notes
- The command-line client provides the fastest path for a developer UX
- We can start with some simple commands around signup and app creation
- Developers exist on a per cafe basis (at least to start... though is there a need to make these objects also exist on the network?)
- Applications are given access to user's threads

### Starting points
- Define the data model of a `Developer` (look at old Set structures)
- Define data model of an `Application` (look at old Set structures)

Does that about cover the initial motivations @asutula?

**Comment by asutula** [comment]
Yea I think that captures the main ideas 👍

**Comment by sanderpick** [comment]
To clarify, we don't need to solve billing _right now_. However, there's still some fuzziness here around how to to verify a signup:

Some options:
  - The tried and true way is with something like GH OAuth
  - @carsonfarmer is exploring DID here and will reach out to IPFS to see if they have any recommendations (we want to signal that we're thinking about better solutions)
  - Others?

**Comment by balupton** [comment]
So I was doing some research on this yesterday, here are the takeways.

For oauth and go, seems t[here is only one game in town](https://github.com/search?q=go+oauth) for oauth 2:

- https://github.com/golang/oauth2

Example config for github:

- https://github.com/andrewtian/golang-github-oauth-example

---

Instead of GitHub Auth, which is only useful for us as devs use github, I was considering for longer-term and with our ambitions of this entire epic, to knock of all the stones, we could do Coinbase Connect OAuth instead:

- https://developers.coinbase.com/docs/wallet/coinbase-connect

We can charge in USD from whatever wallet that the user selects. The user controls the payment limits - be it daily or monthly - and we can deduct at any point we want.

They even have clients for mobile:

- https://developers.coinbase.com/docs/wallet/coinbase-connect/mobile

And as coinbase supports USDC, there and we can bill USD from the user's selected USDC wallet, there is no crypto fluctuation either.

So this could be quite feasible for knocking off auth+payment, rather than github+stripe combo

**Comment by carsonfarmer** [comment]
For developer accounts, maybe the overhead of Coinbase isn't so bad? Obvi for users, this overhead is too much, but for developers, maybe not?

**Comment by carsonfarmer** [comment]
We have a meeting with IPFS/PL regarding DiD later this week, but the TL;DR on the research front here is we have three options:
1. Use an existing _single_ (somewhat centralized) ident system such as Coinbase, Keybase, 3Box, etc
2. Use something like IPID via IDM (or directly), which would require some work on our part or waiting
3. Stick with standard web2 options for now, and then move to a 'universal' DiD system (such as IDM) at a later date

**Comment by sanderpick** [comment]
More thinking here: https://paper.dropbox.com/doc/Apps-and-Services--AfMzq7v_JQt~0tpmzTYvJz49Ag-s5iy3LYOBXDyUs6RQICEk
